# Generated by Django 4.2.30 on 2026-04-25 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', "To'lov kutilmoqda / Yangi"), ('CONFIRMED', 'Rasmiylashtirildi'), ('PACKING', "Yig'ilmoqda"), ('SHIPPING', "Yo'lda"), ('DELIVERED', 'Yetib keldi'), ('CANCELLED_BY_USER', 'Foydalanuvchi bekor qildi'), ('CANCELLED_BY_ADMIN', 'Admin bekor qildi'), ('SYSTEM_AUTO_CANCEL', 'Tizim avtomatik bekor qildi')], default='PENDING', max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=32)),
                ('to_status', models.CharField(choices=[('PENDING', "To'lov kutilmoqda / Yangi"), ('CONFIRMED', 'Rasmiylashtirildi'), ('PACKING', "Yig'ilmoqda"), ('SHIPPING', "Yo'lda"), ('DELIVERED', 'Yetib keldi'), ('CANCELLED_BY_USER', 'Foydalanuvchi bekor qildi'), ('CANCELLED_BY_ADMIN', 'Admin bekor qildi'), ('SYSTEM_AUTO_CANCEL', 'Tizim avtomatik bekor qildi')], max_length=32)),
                ('actor_type', models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('SYSTEM', 'System')], default='SYSTEM', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_history_events', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
