# Generated by Django 4.2.30 on 2026-05-18 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_order_credit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Karta (Click/Payme)'), ('credit', "Muddatli to'lov")], default='cash', max_length=20),
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Yechilgan summa')),
                ('reason', models.CharField(max_length=255, verbose_name='Maqsad/Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana va vaqt')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='Kassir (Admin)')),
            ],
            options={
                'verbose_name': 'Kassa chiqimi (Withdrawal)',
                'verbose_name_plural': 'Kassa chiqimlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
