# Generated by Django 4.2.30 on 2026-05-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_payment_method_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('AWAITING_PAYMENT', "To'lov kutilmoqda (karta)"), ('PENDING', 'Yangi buyurtma'), ('CONFIRMED', 'Tasdiqlandi'), ('PACKING', "Yig'ilmoqda"), ('SHIPPING', "Yo'lda (kuryerda)"), ('DELIVERED', 'Yetkazildi (eshikda)'), ('RECEIVED', 'Xaridorga topshirildi'), ('CANCELLED_BY_USER', 'Foydalanuvchi bekor qildi'), ('CANCELLED_BY_ADMIN', 'Admin bekor qildi'), ('SYSTEM_AUTO_CANCEL', 'Tizim avtomatik bekor qildi')], default='PENDING', max_length=32),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='to_status',
            field=models.CharField(max_length=32),
        ),
    ]
