# Generated by Django 4.2.30 on 2026-06-02 09:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_order_status_idx_order_order_created_at_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Yetkazib berish nuqtasi kengligi (GPS, -90...90)', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))]),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Yetkazib berish nuqtasi uzunligi (GPS, -180...180)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))]),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='delivery_photo',
            field=models.ImageField(blank=True, help_text='Kuryer tomonidan yetkazib berish paytida olingan rasm', null=True, upload_to='orders/delivery_proof/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='received_code_verified',
            field=models.BooleanField(blank=True, db_index=True, help_text="Mijoz tomonidan kuryerga ayttirilgan qabul kodi to'g'ri kiritilganmi (null = bu transition uchun amal qilmaydi)", null=True),
        ),
    ]
