# Generated by Django 4.2.30 on 2026-06-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_delivery_proof_phase_2_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispute_deadline',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Shu vaqtgacha mijoz disput ocha oladi (DELIVERED + 7 kun)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='received_code',
            field=models.CharField(blank=True, help_text="Kuryer mijozdan so'raydigan 6 xonali yetkazib berish kodi", max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='received_code_sent_at',
            field=models.DateTimeField(blank=True, help_text="Qabul kodi SMS'da yuborilgan vaqt", null=True),
        ),
    ]
