# Generated by Django 4.2.30 on 2026-06-02 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0010_received_code_dispute_phase_2_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Mijoz shikoyatining tafsiloti')),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('under_review', "Ko'rib chiqilmoqda"), ('resolved_for_customer', 'Mijoz foydasiga hal qilindi'), ('resolved_for_business', 'Biznes foydasiga hal qilindi')], db_index=True, default='open', max_length=32)),
                ('resolution_note', models.TextField(blank=True, default='', help_text="Admin tomonidan qaror sababi va batafsil ma'lumot")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderDisputeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=orders.models._dispute_image_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='orders.orderdispute')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='orderdispute',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderdispute',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='Qaror qabul qilgan admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='orderdispute',
            index=models.Index(fields=['status', '-created_at'], name='dispute_status_created_idx'),
        ),
    ]
