# Generated by Django 4.2.30 on 2026-06-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_dispute_phase_2_6'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credit_overdue_pardoned',
            field=models.BooleanField(db_index=True, default=False, help_text='Admin tomonidan ban hisobiga kiritilmaslik uchun belgilangan.'),
        ),
    ]
