# Generated by Django 4.2.30 on 2026-06-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_drop_credit_overdue_pardoned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='credit_due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_credit',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('AWAITING_PAYMENT', "To'lov kutilmoqda (karta)"), ('PENDING', 'Yangi buyurtma'), ('CONFIRMED', 'Tasdiqlandi'), ('PACKING', "Yig'ilmoqda"), ('SHIPPING', "Yo'lda (kuryerda)"), ('DELIVERED', 'Yetkazildi (eshikda)'), ('RECEIVED', 'Xaridorga topshirildi'), ('CANCELLED_BY_USER', 'Foydalanuvchi bekor qildi'), ('CANCELLED_BY_ADMIN', 'Admin bekor qildi'), ('SYSTEM_AUTO_CANCEL', 'Tizim avtomatik bekor qildi')], db_index=True, default='PENDING', max_length=32),
        ),
    ]
