# Generated by Django 4.2.30 on 2026-06-22 11:53

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0017_order_updated_at_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(blank=True, db_index=True, default='', max_length=24, unique=True)),
                ('initiator_role', models.CharField(choices=[('admin', 'Admin'), ('courier', 'Kuryer'), ('customer', 'Mijoz')], default='admin', max_length=16)),
                ('customer_request_note', models.TextField(blank=True, default='', help_text="Admin mijoz so'rovini yozib qoladi (telefon orqali bo'lsa)")),
                ('reason_code', models.CharField(choices=[('defective', 'Aybli (defective)'), ('wrong_item', "Noto'g'ri mahsulot"), ('not_as_described', 'Tavsifga mos emas'), ('damaged_in_transit', "Yo'lda buzildi"), ('quality_issue', 'Sifat masalasi'), ('size_mismatch', "O'lcham to'g'ri kelmadi"), ('changed_mind', "Fikr o'zgardi"), ('duplicate_order', 'Takroriy buyurtma'), ('customer_refused', 'Mijoz qabul qilmadi')], db_index=True, max_length=32)),
                ('reason_text', models.TextField(blank=True, default='', help_text='Sabab batafsil (admin yoki mijoz)')),
                ('status', models.CharField(choices=[('REQUESTED', "So'rov yuborildi"), ('APPROVED', 'Tasdiqlandi'), ('PICKUP_SCHEDULED', 'Kuryer biriktirildi'), ('PICKED_UP', 'Tovar olindi'), ('INSPECTING', 'Tekshirilmoqda'), ('ACCEPTED', 'Qabul qilindi'), ('REFUNDED', 'Pul qaytarildi'), ('REPLACED', 'Almashtirildi'), ('REJECTED', 'Rad etildi'), ('CANCELLED', 'Bekor qilindi')], db_index=True, default='REQUESTED', max_length=32)),
                ('status_changed_at', models.DateTimeField(auto_now=True)),
                ('pickup_address', models.TextField(blank=True, default='')),
                ('pickup_at', models.DateTimeField(blank=True, null=True)),
                ('inspection_at', models.DateTimeField(blank=True, null=True)),
                ('inspection_notes', models.TextField(blank=True, default='')),
                ('refund_method', models.CharField(blank=True, choices=[('cash', 'Naqd (kassa)'), ('card', 'Karta'), ('click', 'Click'), ('payme', 'Payme'), ('store_credit', "Do'kon balansi"), ('replacement', 'Almashtirish')], default='', help_text='Yakuniy refund usuli (ACCEPTED dan keyin tanlanadi)', max_length=16)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Mijozga qaytarilgan summa (UZS)', max_digits=12)),
                ('refund_reference', models.CharField(blank=True, default='', help_text='Bank tranzaksiya raqami / Payme refund ID / Withdrawal #', max_length=255)),
                ('refund_processed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispute', models.ForeignKey(blank=True, help_text="Agar shu disputdan kelib chiqqan bo'lsa", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='orders.orderdispute')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_initiated', to=settings.AUTH_USER_MODEL)),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_inspected', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.order')),
                ('pickup_courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_pickup', to=settings.AUTH_USER_MODEL)),
                ('refund_processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_refund_processed', to=settings.AUTH_USER_MODEL)),
                ('replacement_order', models.OneToOneField(blank=True, help_text='Almashtirish uchun yaratilgan yangi buyurtma', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_of', to='orders.order')),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_status_changed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='returned_qty',
            field=models.PositiveIntegerField(default=0, help_text='Necha donasi qaytarib olingan (refunded yoki replaced)'),
        ),
        migrations.CreateModel(
            name='OrderReturnPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=orders.models._return_photo_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('claim', "Da'vo (claim) rasmi"), ('inspection', 'Tekshiruv rasmi')], default='claim', max_length=16)),
                ('return_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='orders.orderreturn')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_photos_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('refund_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('condition', models.CharField(choices=[('new', 'Yangi (ochilmagan)'), ('used_open', 'Ochilgan'), ('used_damaged', 'Zararlangan'), ('defective', 'Aybli')], default='new', max_length=16)),
                ('restock', models.BooleanField(default=True, help_text="Tovar stokka qaytariladimi (False bo'lsa writeoff)")),
                ('writeoff_reason', models.CharField(blank=True, choices=[('', "Yo'q (stokka qaytarildi)"), ('defect', 'Aybli — writeoff'), ('lost', "Yo'qotildi"), ('customer_fault', 'Mijoz aybi — write-off')], default='', max_length=32)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_entries', to='orders.orderitem')),
                ('return_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orderreturn')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['order_item'], name='return_item_order_item_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='orderreturn',
            index=models.Index(fields=['status', '-created_at'], name='return_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='orderreturn',
            index=models.Index(fields=['order', 'status'], name='return_order_status_idx'),
        ),
    ]
