# Generated by Django 4.2.30 on 2026-06-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_return_phase_3_1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id']},
        ),
    ]
