# Generated by Django 4.2.30 on 2026-06-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_orderitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_type',
            field=models.CharField(choices=[('retail', 'Oddiy narx'), ('discount', 'Chegirma narx'), ('optom', 'Optom narx'), ('master', 'Usta narx')], default='retail', max_length=12),
        ),
    ]
