release: python manage.py collectstatic --noinput && python manage.py migrate --noinput && python manage.py sync_superusers
web: gunicorn core.wsgi --workers 2 --max-requests 1000 --max-requests-jitter 100 --bind 0.0.0.0:$PORT --timeout 120 --log-level info
