# Generated by Django 4.2.30 on 2026-04-28 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_is_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.CharField(blank=True, default='', max_length=320)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='banners/products/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='banners/backgrounds/')),
                ('background_color', models.CharField(default='#111827', max_length=32)),
                ('accent_color', models.CharField(default='#007a4d', max_length=32)),
                ('button_label', models.CharField(default="Mahsulotni ko'rish", max_length=80)),
                ('button_url', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_banners', to='products.product')),
            ],
            options={
                'ordering': ['order', '-updated_at', '-id'],
            },
        ),
    ]
