# Generated by Codex on 2026-04-29

from datetime import timedelta

from django.db import migrations


def shift_existing_banner_times(apps, schema_editor):
    HomeBanner = apps.get_model('products', 'HomeBanner')
    for banner in HomeBanner.objects.all():
        update_fields = []
        if banner.start_date:
            banner.start_date = banner.start_date - timedelta(hours=5)
            update_fields.append('start_date')
        if banner.end_date:
            banner.end_date = banner.end_date - timedelta(hours=5)
            update_fields.append('end_date')
        if update_fields:
            banner.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_homebanner'),
    ]

    operations = [
        migrations.RunPython(shift_existing_banner_times, migrations.RunPython.noop),
    ]
