# Generated by Django 4.2.30 on 2026-05-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_globalsetting_product_discount_price_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
