# Generated by Django 4.2.30 on 2026-05-23 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_category_name_en_category_name_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/logos/')),
                ('is_popular', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Telefon brandi',
                'verbose_name_plural': 'Telefon brendlari',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PhoneSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='products.phonebrand')),
            ],
            options={
                'verbose_name': 'Telefon seriyasi',
                'verbose_name_plural': 'Telefon seriyalari',
                'ordering': ['order', 'name'],
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Variant nomi: 'Pro', 'Pro Max', 'Ultra', 'Plus', yoki bo'sh (standart)", max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, help_text='Chiqarilgan yil', null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='products.phoneseries')),
            ],
            options={
                'verbose_name': 'Telefon modeli',
                'verbose_name_plural': 'Telefon modellari',
                'ordering': ['order', 'name'],
                'unique_together': {('series', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, help_text="Ixtiyoriy izoh: 'Faqat eSIM versiyasi', 'A2342 model uchun'", max_length=255)),
                ('phone_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatible_products', to='products.phonemodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility', to='products.product')),
            ],
            options={
                'verbose_name': 'Moslik',
                'verbose_name_plural': 'Moslik matritsasi',
                'ordering': ['phone_model__series__brand__order', 'phone_model__series__order', 'phone_model__order', 'phone_model__name'],
                'unique_together': {('product', 'phone_model')},
            },
        ),
    ]
