# Generated by Django 4.2.30 on 2026-05-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_phone_compatibility_matrix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='name',
            field=models.CharField(blank=True, default='', help_text="Variant nomi: 'Pro', 'Pro Max', 'Ultra', 'Plus', yoki bo'sh (standart)", max_length=100),
        ),
    ]
