# Generated by Django 4.2.30 on 2026-06-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_search_trgm_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='shelf_location',
            field=models.CharField(blank=True, default='', help_text="Do'kondagi jismoniy polka manzili (masalan: '001'). FAQAT admin paneli va POS'da ko'rinadi.", max_length=20),
        ),
    ]
