# Generated by Django 4.2.30 on 2026-06-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_add_variant_shelf_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shelf_location',
            field=models.CharField(blank=True, default='', help_text="Do'kondagi polka manzili (variantsiz mahsulot uchun yoki barcha variantlar bir polkada bo'lsa default). FAQAT admin paneli, POS va Buyurtmalarda ko'rinadi.", max_length=20),
        ),
    ]
