# Generated by Django 4.2.30 on 2026-07-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_product_optom_price_product_optom_price_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, default='', help_text="Kimdan kelgan (yetkazib beruvchi). FAQAT admin va POS'da ko'rinadi — foydalanuvchiga ko'rinmaydi.", max_length=100),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='supplier',
            field=models.CharField(blank=True, default='', help_text="Kimdan kelgan (yetkazib beruvchi). FAQAT admin va POS'da.", max_length=100),
        ),
    ]
