# Generated by Django 4.2.30 on 2026-04-24 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_category_is_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('search_terms', models.JSONField(blank=True, default=list)),
                ('keyword_scores', models.JSONField(blank=True, default=dict)),
                ('category_scores', models.JSONField(blank=True, default=dict)),
                ('product_scores', models.JSONField(blank=True, default=dict)),
                ('price_bucket_scores', models.JSONField(blank=True, default=dict)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('event_type', models.CharField(choices=[('search', 'Search'), ('view', 'View'), ('cart', 'Cart'), ('order', 'Order')], max_length=20)),
                ('query_text', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.FloatField(default=1.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='recommendations.recommendationprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
