# Generated by Django 4.2.30 on 2026-06-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recommendationevent',
            index=models.Index(fields=['user', 'event_type', '-created_at'], name='recommendat_user_id_da5f53_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationevent',
            index=models.Index(fields=['guest_session_id', 'event_type', '-created_at'], name='recommendat_guest_s_651d3f_idx'),
        ),
    ]
