# Generated by Django 4.2.30 on 2026-05-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_normalize_phone_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='delivery_address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
