# Generated by Django 4.2.30 on 2026-05-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('seller', 'Sotuvchi'), ('courier', 'Kuryer'), ('warehouse', 'Omborchi'), ('cashier', 'Kassir')], db_index=True, help_text="Xodim roli. Bo'sh bo'lsa — oddiy foydalanuvchi.", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Foydalanuvchi telefon raqamini tasdiqlagan.'),
        ),
    ]
