# Generated by Django 4.2.30 on 2026-05-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_role_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_invalidated_at',
            field=models.DateTimeField(blank=True, help_text="Rol o'zgartirilgan vaqt. Bundan oldingi tokenlar bekor bo'ladi.", null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('seller', 'Sotuvchi'), ('courier', 'Kuryer')], db_index=True, help_text="Xodim roli. Bo'sh bo'lsa — oddiy foydalanuvchi.", max_length=20, null=True),
        ),
    ]
