# Generated by Django 4.2.30 on 2026-05-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_role_invalidated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_master',
            field=models.BooleanField(db_index=True, default=False, help_text='Usta foydalanuvchi. Barcha mahsulotlarda 5% chegirma oladi.'),
        ),
    ]
