# Generated by Django 4.2.30 on 2026-07-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_ensure_superusers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role_invalidated_at',
            new_name='tokens_invalidated_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='tokens_invalidated_at',
            field=models.DateTimeField(blank=True, help_text='Tokenlar bekor qilingan vaqt. Bundan oldingi tokenlar xavfsizlik yuzasidan ishlamaydi.', null=True),
        ),
    ]
